language: go

go:
- 1.12.x

install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get github.com/go-playground/overalls

env:
- GO111MODULE=on

script:
- go test -v ./...
- $HOME/gopath/bin/overalls -project=github.com/autograde/aguis -covermode=count -debug
- $HOME/gopath/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
