ignored = ["github.com/Sirupsen/logrus"]

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/labstack/echo"

[[constraint]]
  branch = "master"
  name = "github.com/markbates/goth"

[[constraint]]
  branch = "master"
  name = "github.com/xanzy/go-gitlab"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "github.com/docker/docker"

[[override]]
  branch = "master"
  name = "github.com/docker/distribution"

[[override]]
  branch = "master"
  name = "github.com/docker/go-connections"